### ISSUE TITLE
8 - persist the keyboard statuses on each row play

### ISSUE THREAD

**Issue by LindaKeating** [LindaKeating/foclach-netlify#14]
When in daily mode persist the keyboard letter statuses to local storage on each play of the row.  

How to test
1. Play a couple of rows of the game
2. Refresh the browser
=> the keyboard should show the status colours that were present before the browser refresh

**Comment by ThatGuyHughesy** [comment]
Hi @LindaKeating, thanks for Foclach! I noticed this issue and can fix it if it's not currently being worked on.

**Comment by LindaKeating** [comment]
Consider yourself assigned!  Míle Buíochas!
